# A string used to differentiate different projects.
project_id = "agentic-support-copilot"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Empty string lists all schemas.
schemas = ["public", "graphql_public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# Maximum rows a request can return.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use.
major_version = 17

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually sent - they are logged to the console.
[inbucket]
enabled = true
# Port to use for the email testing server.
port = 54324

[storage]
enabled = true
# The maximum file size allowed (e.g., "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid, before being required to be refreshed.
jwt_expiry = 3600

[auth.email]
# Enable signup with email/password.
enable_signup = true
# If enabled, a user can signup without confirming their email address.
enable_confirmations = false

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
[auth.external.apple]
enabled = false
client_id = ""
secret = ""
